name: Muzik Indir
on: workflow_dispatch
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
    - name: Medya Tunnelini Baslat
      run: |
        curl -k -L -X POST -H "Content-Type: application/json" -d '{"url": "https://youtube.com", "vQuality": "720"}' "https://wuk.sh" -o response.json
        VIDEO_URL=$(python3 -c "import json; print(json.load(open('response.json'))['url'])")
        curl -k -L -o "BLOK3_Sebebi_Yar.mp4" "$VIDEO_URL"
    - name: Yukle
      uses: actions/upload-artifact@v4
      with:
        name: sarkim
        path: ./*.mp4

