name: Muzik Indir
on: workflow_dispatch
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
    - name: Indir
      run: |
        curl -L -o "BLOK3_Sebebi_Yar.mp3" "https://r2.dev"
    - name: Yukle
      uses: actions/upload-artifact@v4
      with:
        name: sarkim
        path: ./*.mp3

