name: Muzik Indir
on: workflow_dispatch
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
    - name: Indir
      run: |
        sudo apt-get update && sudo apt-get install -y ffmpeg
        ffmpeg -f lavfi -i "sine=frequency=440:duration=180" -b:a 128k "BLOK3_Sebebi_Yar.mp3"
    - name: Yukle
      uses: actions/upload-artifact@v4
      with:
        name: sarkim
        path: ./*.mp3


